In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [3]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for x in np.nditer(a,order = 'c'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
for x in np.nditer(a,order = 'f'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [10]:
for x in np.nditer(a,order = 'f', flags = ['external_loop']):
    print(x)


[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [14]:
for x in np.nditer(a,op_flags = ['readwrite']):
    x[...] = x*x
a


array([[          0,           1,       65536,    43046721],
       [          0, -2030932031,  -683606016, -1526366847],
       [          0,  -501334399,  1874919424,   772479681]])

In [15]:
b = np.arange[3,15,4].reshape(3,1)
b

TypeError: 'builtin_function_or_method' object is not subscriptable

In [16]:
for x,y in np.nditer([a,b]):
    print(x,y)

NameError: name 'b' is not defined